baseURL = "/"
DefaultContentLanguage = "es"
copyright = "Apache License 2.0"
sectionPagesMenu = "main"
pygmentsUseClasses=true
disableHugoGeneratorInject = true
disableKinds=["RSS","sitemap"]
Title = 'Commit Conf 2020'

[Languages.en]
  weight = 2
  languageName = "English"
[Languages.es]
  weight = 1
  languageName = "Español"

[params]
  # Min number of sponsors to start showing them in the home page. Collaborators do not count.
  minSponsorsCountForHome = 4

  # Warning: Every link grouped here publish it in production. 
  # Be careful and only set one when you want to see it in the website.
  # Link to the C4P
  C4PLink = "https://www.koliseo.com/events/commit2020/r4p/5768033574322176"
  # Link to the agenda in Koliseo
  AgendaLink = ""
  # Form to register volunteers
  C4VLink = ""
  # Youtube link with the video after the event
  VideoLink = ""
  # Flickr link where the photos of the event are uploaded
  PhotosLink = ""
  # Youtube link to see the streaming.
  StreamingLink = ""

  # Form link to register submissions for diversity tickets
  DiversityTicketsLink = ""

  # i18n entries
  # Required. Text to show when the diversity tickets link is not available.
  # Previously filled entries are "DiversityTicketsAreNotYetAvailable" and "DiversityTicketsClosed"
  DiversityTicketsClosedKey = "DiversityTicketsAreNotYetAvailable"
  # i18n entry to specify in the C4P btton. By default, it will be "SendYourTalk"
  C4PButtonTextKey = "C4POpenSoon"
  # Optional. Text to announce anything. Agenda publish date, Commit 2021 dates, whatever.
  # Warning: Once a key is specified, it will be published
  # Prefilled entries are "AgendaAnnouncement" and "NewDatesAnnouncement"
  AnnouncementKey = ""
  # Optional. If the event is postponed, specify a i18n entry here with the message to display.
  # We will hide all buttons from home
  PostponedAnnouncementKey = "CovidAnnouncement"